# Site settings
title: Visual Data Analysis Lab
author:
  name: Jan Aerts
  email: jan.aerts@kuleuven.be
description: > # this means to ignore newlines until "baseurl:"
  Augmenting Intelligence - Making sense of complex data
url: "http://vda-lab.io" # the base hostname & protocol for your site
twitter_username: jandot
permalink: /:year/:month/:title
logo: /assets/vda-lab_logo.png

# Build settings
markdown: kramdown

plugins:
- jekyll-seo-tag

exclude:
  - svelte-components
