
slides.html : slides.md
	pandoc -t revealjs slides.md -o slides.html --slide-level=1 --variable theme=default --variable revealjs-url=../reveal.js -s --variable theme=blood --variable transition=fade --template reveal-template.html --no-highlight --variable hlss=zenburn
